### ISSUE TITLE
[FABRIC] Bug with Prism

### ISSUE THREAD

**Issue by Lolothepro** [AbsolemJackdaw/AppleCrates#14]
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.RuntimeException: Error creating Mixin config modid.mixins.json for mod applecrates
	at org.quiltmc.loader.impl.launch.common.QuiltMixinBootstrap.init(QuiltMixinBootstrap.java:113)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:147)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	... 9 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config modid.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at org.quiltmc.loader.impl.launch.common.QuiltMixinBootstrap.init(QuiltMixinBootstrap.java:111)
	... 12 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'modid.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 15 more
```

**Comment by AbsolemJackdaw** [comment]
fixed the fabric josn, forgot to change the mixin file ref when fixin another crash. 
verison has been pushed and should be available in a couple minutes.
