### ISSUE TITLE
Major issues with 2.12.1 for Forge 1.19.2

### ISSUE THREAD

**Issue by katubug** [AbsolemJackdaw/AppleCrates#35]
Hi! So I have an existing server and recently updated AppleCrates from 2.10.0 to 2.12.1, and now behavior is totally borked. Existing Apple Crates appear to have contents visually, but when interacted with, the UI shows nothing, as seen below:

![2024-10-04_11 10 07](https://github.com/user-attachments/assets/97a9396e-200e-47a6-a586-2162024723ae)
![2024-10-04_11 10 05](https://github.com/user-attachments/assets/90002033-553a-4b70-aab5-c0cf89976b40)

Newly placed Apple Crates seem to be random when they will display items for sale. After interacting with an Apple Crate, the player glitches out on the server and cannot use keybinds, open their Curios or Backpacks, or teleport with commands etc.

Here is my full latest.log and debug.log: https://gist.github.com/katubug/ce8ec0f98dbc7610153fa9152a865002

I think the relevant bit of the log is:
```
[04Oct2024 16:14:46.566] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@40c3bcbc, suppressing error
java.lang.RuntimeException: Slot 30 not in valid range - [0,30)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:206) ~[forge-1.19.2-43.4.4-universal.jar%23752!/:?]
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:58) ~[forge-1.19.2-43.4.4-universal.jar%23752!/:?]
	at net.minecraftforge.items.SlotItemHandler.m_7993_(SlotItemHandler.java:40) ~[forge-1.19.2-43.4.4-universal.jar%23752!/:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_38946_(AbstractContainerMenu.java:168) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.m_38893_(AbstractContainerMenu.java:123) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.server.level.ServerPlayer.m_143399_(ServerPlayer.java:382) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraftforge.network.NetworkHooks.openScreen(NetworkHooks.java:207) ~[forge-1.19.2-43.4.4-universal.jar%23752!/:?]
	at jackdaw.applecrates.block.CrateBlock.openOwnerUI(CrateBlock.java:32) ~[Apple%20Crates-forge-1.19.2-2.12.1.jar%23444!/:2.12.1]
	at jackdaw.applecrates.block.CrateBlockBase.m_6227_(CrateBlockBase.java:185) ~[Apple%20Crates-forge-1.19.2-2.12.1.jar%23444!/:2.12.1]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:714) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:340) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1060) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23747!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

Thanks for your time, and for the great mod!

**Comment by AbsolemJackdaw** [comment]
I hope you made a backup :s 

I think I know where the issue comes from, and it's got everything to do with the updating.
The old versions still store only 29 slots, the new updated crates come with an extra slot.

Hopefully you can load a backup, and i'll include a safety check for the slot amount, so that old crates get a fix. 
Feel free to join my discord, so we can chat about the issue. 

I'm at your disposition for further questions
